# Generated by Django 3.2.22 on 2023-10-20 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 56, 48, 103127), verbose_name='date joined'),
        ),
    ]
