# Generated by Django 3.2.22 on 2023-10-21 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 11, 26, 53, 420564), verbose_name='date joined'),
        ),
    ]
