# Generated by Django 3.2.22 on 2023-10-22 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20231022_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 8, 52, 13, 478267), verbose_name='date joined'),
        ),
    ]
