# Generated by Django 3.2.22 on 2023-10-22 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20231022_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 14, 28, 5, 123849), verbose_name='date joined'),
        ),
    ]
