# Generated by Django 3.2.22 on 2023-10-22 20:11

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231022_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/profile_images/default.jpg', null=True, upload_to=core.models.profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 21, 11, 20, 93709), verbose_name='date joined'),
        ),
    ]
