# Generated by Django 3.2.22 on 2023-10-22 20:14

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20231022_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/profile_images/default.png.jpg', null=True, upload_to=core.models.profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 21, 14, 58, 852737), verbose_name='date joined'),
        ),
    ]
