# Generated by Django 3.2.22 on 2023-10-24 22:13

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20231024_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='large_image',
            field=models.ImageField(default='uploads/products/1.jpg', height_field=500, null=True, upload_to=core.models.product_image_file_path, width_field=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 23, 13, 14, 165991), verbose_name='date joined'),
        ),
    ]
