# Generated by Django 3.2.22 on 2023-10-24 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20231024_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 23, 14, 38, 663686), verbose_name='date joined'),
        ),
    ]
