# Generated by Django 3.2.22 on 2023-10-24 22:16

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='large_image',
            field=models.ImageField(default='uploads/products/1.jpg', height_field='500', null=True, upload_to=core.models.product_image_file_path, width_field='500'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 23, 16, 1, 756253), verbose_name='date joined'),
        ),
    ]
