# Generated by Django 3.2.22 on 2023-10-24 22:24

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20231024_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='large_image',
            field=models.ImageField(default='uploads/products/1.jpg', null=True, upload_to=core.models.product_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 23, 24, 33, 216850), verbose_name='date joined'),
        ),
    ]
