---
name: Test, Manage

on: [push]

jobs:
  build:
    name: Tests and Run
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tests
        run: python manage test.py

      - name: execute py script
        run: python manage.py